### ISSUE TITLE
Eliminar reenvío de aviso en casino

### ISSUE THREAD

**Issue by PhirotoK** [NiciusB/MegaMegamagnate#1]
Cuando tienes el autoclick en los casinos activado, surge un mensaje que cuando le das a "aceptar" se reenvía, obligándote a actualizar la página. Esto ocurre en 3 situaciones:
- Cuando consigues los 3 botes.
- Cuando el casino consigue los 10 botes diarios.
- Cuando el casino consigue los 50 botes.

Propongo que, cuando ocurra una de estas situaciones y surja el mensaje, al darle a aceptar te envíe a la lista de casinos (igual que ocurre cuando el casino logra un Bote!).

**Comment by PhirotoK** [comment]
Habría que hacer exactamente lo mismo con el aviso del HiLo, el de que ya has hecho las 100 partidas. Que te mande a la lista de casinos.

**Comment by DamageESP** [comment]
Solución implementada en 612a4e7. Simplemente detiene el modo Auto. He decidido no redireccionar ya que el usuario puede querer canjear fichas en el casino que está jugando o no, o simplemente no quiere que se le redirija.
