### ISSUE TITLE
Añadir botón "Activar todo" en Líderes.

### ISSUE THREAD

**Issue by PhirotoK** [NiciusB/MegaMegamagnate#2]
Habéis añadido la posibilidad de Activar las habilidades del líder sin ningún tipo de traba (mensajes, actualización de página, ...). Sin embargo, aún sigue siendo en parte un coñazo por tener que clicar a "Activar" unas 10 veces (por ahora, más tarde serán 20, 30, 40, ...).

Propongo un botón al lado del botón "Activar" que se llame "Activar todo" (o algo así) y que provoque que la energía se gaste completamente en esa habilidad instantáneamente. 

Pd: En caso de hacerse, entiendo que el mensajito que aparece a la derecha también habría que cambiarlo de forma que si se pulsa a "Activar todo", en vez de aparecer muchos mensajitos, aparezca sólo uno donde ponga los sabots totales, exp total ganada, ...

**Comment by DamageESP** [comment]
Añadido en 88df438.
