### ISSUE TITLE
Añadir un porcentaje o factor de rentabilidad en Edificios.

### ISSUE THREAD

**Issue by PhirotoK** [NiciusB/MegaMegamagnate#3]
Esto ya lo hablé con Damageesp. La idea quizás no está del todo desarrollada, quizás vosotros podáis desarrollarla más.
El caso viene siendo que actualmente hay añadido un porcentaje de Eficiencia a la hora de construir un edificio. Omitiendo el hecho de que te puedan atacar y todo eso, basarse siempre en la Eficiencia sería lo que lograría los mejores resultados en cuanto a usar tu dinero de forma rentable para subir ingresos. Sin embargo, al añadir la "variable" ataques, resulta que a veces vale la pena construir edificios con menor Eficiencia que las Industrias o los Centros Comerciales, simplemente por evitar tener muchos de estos 2 últimos y que así no te ataquen (o tener menos probabilidades de que lo hagan, vamos...).
No existe ninguna forma de calcular la cantidad óptima de edificios que se deberían de tener de cada tipo para que no te ataquen, ya que en ello entran muchos factores (tu espionaje, cuántos edificios tienen los demás, lo famoso que eres incluso xdd).

Por lo tanto, propongo añadir un nuevo porcentaje o factor. Este, a diferencia del de Eficiencia, necesita un valor en el que basarse para calcular el factor de todos los edificios. Mi idea es:
La industria siempre tendría factor 1 (porcentaje 100%). 
El factor de los demás edificios se calcula básicamente de la siguiente manera:
-CC: 2xPrecio(CC)/Precio(Ind)
-Gas: 3xPrecio(Gas)/Precio(Ind)
-Ban: 4xPrecio(Ban)/Precio(Ind)
Y así consecutivamente.

Esto vendría a informarnos de cuánto dinero podrían ganar atacándonos, en base al precio de la industria. Me parece que de aquellas hicisteis un simulador que era parecido a esto pero simplemente sacaba los precios, seguro podéis sacar de ahí parte del código. En cualquier caso me parece que ponerlo en forma de precios sería bastante incómodo, porque se verían muchos números por ahí.

Al final este factor serviría como forma de orientarse. Lo óptimo a la hora de construir estaría entre tender a que todos los edificios tengan factor 1, y a su vez construir los edificios más eficientes. El punto medio que escojamos ya será algo subjetivo.

Ale, a leer. Perdonad, que me pasé un poco D:

**Comment by NiciusB** [comment]
Si vas ahora mismo a edificios, verás que ayer añadí un dato más que te dice lo que ganan al atacarte (y arreglado, ahora es de verdad lo que se gana)

Sí que me parece bien hacer un factor teniendo en cuenta tanto eficiencia como dinero que das, aunque habría que mirar la fórmula exacta y que puedas customizarlo igual

**Comment by PhirotoK** [comment]
Anda, ni me había fijado xdd
Pues así vale también, la verdad.

No, no decía lo de hacer un factor que tuviese en cuenta eficiencia y dinero ganado. Sino un factor sobre el dinero ganado (que viene siendo lo que añadiste, pero en forma de factor). Lo de un factor que tuviese en cuenta ambos... Buff, al ser algo subjetivo y tal me parece un poco chorra y quizás algo chungo de hacer. Pero bueh, según usemos el método que hay ahora ya iremos viendo xP

**Comment by DamageESP** [comment]
Con el nuevo dato que ha introducido @NiciusB puedes obtener la misma información que dices (si lo he entendido bien), pero en forma cruda (dinero, y no un porcentaje). Creo que así es más claro y puedes tener más control sobre qué construir si no quieres ser una vaca.
